name: Hello

on: 
  push: 
   branches: [main]

jobs:

  greet:
   runs-on: ubuntu-latest
   steps:
     - name: say hello
       run: echo "Hi to first workflow"

     - name: say hello to username
       run: echo "Hello $USER"

     - name: version 0f docker
       run: docker -v

     - name: Install Python
       run: python -v
