name: hello workflow #workflow name
on:
    workflow_dispatch: #manual trigger
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Hello world!"
      - name: say bye
        run: echo "Bye world!"
      - name: say welcome
        run: echo $user   
      
  